# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        provMe:
            entity:
                class: AppBundle:Utilisateur
                property: email
    encoders:
        AppBundle\Entity\Utilisateur: plaintext
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            pattern: ^/
            # activate different ways to authenticate
            provider: provMe
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login: 
                check_path: /login_check
                login_path: /login
                default_target_path: /tchat
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            logout:
                path:  /logout
                target: /
    access_control:
        - { path: ^/tchat, roles: 'ROLE_USER' }
