# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    tchat:
        class: AppBundle\Service\MessageTchat
#        nom de notre service
    logout_handler:
#        la route du fichier qui contient les methodes pour notre services
        class: AppBundle\Handler\LogoutHandler
